apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    run: resto
  name: resto
spec:
  replicas: 3
  selector:
    matchLabels:
      run: resto
  template:
    metadata:
      labels:
        run: resto
    spec:
      containers:
      - image: dbenque/prom-demo-resto:v3
        imagePullPolicy: IfNotPresent
        name: resto
        ports:
        - containerPort: 8080
          protocol: TCP