apiVersion: v1
kind: Service
metadata:
  labels:
    app: resto
  name: resto
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: resto  
  type: NodePort
