apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: restomonitoring
  labels:
    k8s-app: resto
spec:
  selector:
    matchLabels:
      app: resto
  endpoints:
  - port: web
    interval: 10s
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - default
